version: '3'

services:
  web:
    build: .
    container_name: coffee-shop-web
    command: node_modules/.bin/nodemon --exec npm start
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - database
    links:
      - database

  database:
    image: mongo
    container_name: coffee-shop-database
    ports:
      - '27017:27017'
    volumes:
      - ./_db_data/:/data/db